### ISSUE TITLE
q/esc to close snipe

### ISSUE THREAD

**Issue by craigdallimore** [kungfusheep/snipe-lsp.nvim#2]
Hello! Great plugin.

I noticed that snipe will close when I press `esc`, but `snipe-lsp` does not. Is there a way to set that up, or is it not an available feature?

**Comment by kungfusheep** [comment]
Hey! I've found I didn't have the same problem until I looked at my setup and found the below - if I remove this then both snipe and snipe-lsp work incorrectly?

```
snipe.ui_select_menu:add_new_buffer_callback(function(m)
     vim.keymap.set("n", "<esc>", function()
	m:close()
     end, { nowait = true, buffer = m.buf })
end)
```

**Comment by leath-dub** [comment]
yeah snipe doesn't set this up when you use it as a input menu, most of "defaults" only apply to the buffer menu.

**Comment by kungfusheep** [comment]
ok I've dropped this into #3 will merge later on today

**Comment by craigdallimore** [comment]
Installed the update, it works beautifully. Thank you ❤️
